# Generated by Django 5.1.1 on 2024-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images_order',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
