# Generated by Django 5.1.1 on 2024-11-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_images_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images_order',
            new_name='images_layout',
        ),
    ]
