# Generated by Django 5.1.1 on 2024-11-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_images_order_post_images_layout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postcomment',
            old_name='liked_by_author',
            new_name='is_liked_by_author',
        ),
    ]
