# Generated by Django 5.1.1 on 2024-11-14 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_rename_parent_postcomment_comment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audience',
            name='audience_list',
        ),
        migrations.AddField(
            model_name='audience',
            name='users',
            field=models.ManyToManyField(related_name='audience_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
