# Generated by Django 5.1.1 on 2024-12-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_commentlike_comment_alter_post_user_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='posts.post'),
        ),
    ]
