# Generated by Django 5.0 on 2024-01-01 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('image', models.ImageField(blank=True, height_field='image_height', max_length=255, null=True, upload_to='images', width_field='image_width')),
                ('image_thumbnail', models.ImageField(blank=True, height_field='thumbnail_height', null=True, upload_to='images_tumbnails', verbose_name='image_thumbnail', width_field='thumbnail_width')),
                ('image_width', models.IntegerField(default=0)),
                ('image_height', models.IntegerField(default=0)),
                ('thumbnail_width', models.IntegerField(default=0)),
                ('thumbnail_height', models.IntegerField(default=0)),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
            ],
        ),
        migrations.CreateModel(
            name='TaggedFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.IntegerField(default=0)),
                ('left', models.IntegerField(default=0)),
            ],
        ),
    ]
