# Generated by Django 5.1.1 on 2024-11-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='images_order',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
