# Generated by Django 5.1.1 on 2024-11-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image_images_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='images_order',
        ),
        migrations.AddField(
            model_name='image',
            name='order_id',
            field=models.FloatField(default=-1),
        ),
    ]
