# Generated by Django 5.1.1 on 2024-11-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_remove_image_images_order_image_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='order_id',
            field=models.IntegerField(default=-1),
        ),
    ]
